eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://euroku-cus-order.herokuapp.com//eureka/
    instance:
      hostname: euroku-cus-order.herokuapp.com
